mail:
  smtp:
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    port:
      465
admin:
  id: ${ADMIN_ID}
  password: ${ADMIN_PASSWORD}